dataset:
  graph_token_root: graph-token
  task: shortest_path  # cycle_check, shortest_path
  algorithm: er # er, ba, sbm, ws, grid
  use_split_tasks_dirs: true
  data_fraction: 0.1 # fraction of data to use (0.0-1.0), same for train/val/test
  max_len: 600 # maximum sequence length for AutoGraph tokenization

  balance_classes: False
  balance_strategy: soft_oversample  # undersample (match minority), median (match median class size), oversample (match majority), soft_oversample (both under/over sample to mean class size)

model:
  d_model: 16
  nhead: 4
  nlayers: 2
  d_ff: 128
  dropout: 0.1
  max_pos: 600
  num_classes: 7  # 2 for cycle_check, 7 for shortest_path

train:
  batch_size: 128
  epochs: 300
  lr: 0.001
  weight_decay: 0.0001
  seed: 0
  num_workers: 0  # Disabled due to PyG Data pickling issues

output:
  out_dir: runs_agtt
  run_name: agtt-shortest-path

wandb:
  use: true
  project: graph-token
